// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSheGRpNL3nilQZ81Bc5MU1ap7pGa0z_I',
    appId: '1:394944534448:web:a90626b0749e5b1cdd6875',
    messagingSenderId: '394944534448',
    projectId: 'fire-base-connection-da87c',
    authDomain: 'fire-base-connection-da87c.firebaseapp.com',
    storageBucket: 'fire-base-connection-da87c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFL1GvgBpn6nEdlGcCxN9zYBUIdNySQ3A',
    appId: '1:394944534448:android:f214da00ba669f97dd6875',
    messagingSenderId: '394944534448',
    projectId: 'fire-base-connection-da87c',
    storageBucket: 'fire-base-connection-da87c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSBlvTB41vrLOqOZqbBIHqLL7DDtuH-o',
    appId: '1:394944534448:ios:f2afec4ac249bec1dd6875',
    messagingSenderId: '394944534448',
    projectId: 'fire-base-connection-da87c',
    storageBucket: 'fire-base-connection-da87c.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSBlvTB41vrLOqOZqbBIHqLL7DDtuH-o',
    appId: '1:394944534448:ios:f2afec4ac249bec1dd6875',
    messagingSenderId: '394944534448',
    projectId: 'fire-base-connection-da87c',
    storageBucket: 'fire-base-connection-da87c.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSheGRpNL3nilQZ81Bc5MU1ap7pGa0z_I',
    appId: '1:394944534448:web:60b509b553076083dd6875',
    messagingSenderId: '394944534448',
    projectId: 'fire-base-connection-da87c',
    authDomain: 'fire-base-connection-da87c.firebaseapp.com',
    storageBucket: 'fire-base-connection-da87c.firebasestorage.app',
  );
}
